framework:
    secret: '%env(APP_SECRET)%'
    trusted_proxies: '%env(default:127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16:TRUSTED_PROXIES)%'
    trusted_hosts: '%env(default:^(.+)\.render\.com$,localhost:TRUSTED_HOSTS)%'
    http_method_override: false
    handle_all_throwables: true

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    esi: true
    fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
