[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "frankenphp run --config /etc/caddy/Caddyfile --address 0.0.0.0:${PORT} --env=prod"
healthcheckPath = "/"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"