services:
  - type: web
    name: tasksphere
    env: php
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    buildCommand: docker build --target frankenphp_prod -t tasksphere .
    startCommand: |
      php bin/console cache:clear --no-warmup && 
      php bin/console cache:warmup && 
      frankenphp run --config /etc/caddy/Caddyfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        fromSecret: app_secret
      - key: DATABASE_URL
        fromSecret: database_url
      - key: TRUSTED_PROXIES
        value: "127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"