services:
  - type: web
    name: tasksphere
    env: php
    plan: free
    region: frankfurt
    dockerfilePath: Dockerfile
    buildCommand: docker build --target frankenphp_prod -t tasksphere .
    startCommand: |
      php bin/console cache:clear --no-warmup && 
      php bin/console cache:warmup && 
      frankenphp run --config /etc/caddy/Caddyfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_SECRET
        fromSecret: app_secret  # Créez ce secret dans Render
      - key: DATABASE_URL
        fromSecret: database_url